import {
  facebook,
  instagram,
  shieldTick,
  support,
  truckFast,
  twitter,
} from "../assets/icons";
import {
  bigShoe1,
  bigShoe2,
  bigShoe3,
  customer1,
  customer2,
  shoe4,
  shoe5,
  shoe6,
  shoe7,
  shoe8,
  shoe9,
  shoe10,
  shoe11,
  shoe12,
  shoe13,
  shoe14,
  shoe15,
  shoe16,
  shoe17,
  shoe18,
  shoe19,
  shoe20,
  shoe21,
  shoe22,
  shoe23,
  shoe24,
  shoe25,
  shoe26,
  shoe27,
  shoe28,
  shoe29,
  shoe30,
  thumbnailShoe1,
  thumbnailShoe2,
  thumbnailShoe3,
} from "../assets/images";

export const navLinks = [
  { href: "/#home", label: "Home" },
  { href: "/#about-us", label: "About Us" },
  { href: "/#products", label: "Products" },
  // { href: "/contact", label: "Contact Us" },
];

export const shoes = [
  {
    thumbnail: thumbnailShoe1,
    bigShoe: bigShoe1,
  },
  {
    thumbnail: thumbnailShoe2,
    bigShoe: bigShoe2,
  },
  {
    thumbnail: thumbnailShoe3,
    bigShoe: bigShoe3,
  },
];

export const statistics = [
  { value: "1k+", label: "Brands" },
  { value: "500+", label: "Shops" },
  { value: "250k+", label: "Customers" },
];

export const products = [
  {
    id: 1,
    imgURL: shoe4,
    name: "Nike Air Jordan",
    price: "$200.20",
    rating: 4,
  },
  {
    id: 2,
    imgURL: shoe5,
    name: "Nike K-Swiss",
    price: "$210.20",
    rating: 5,
  },
  {
    id: 3,
    imgURL: shoe6,
    name: "Nike Air-100",
    price: "$220.20",
    rating: 4,
  },
  {
    id: 4,
    imgURL: shoe7,
    name: "Smooth N",
    price: "$230.20",
    rating: 5,
  },
];

export const generateRating = (rating) => {
  let starArray = [];
  for (let i = 0; i < rating; i++) {
    starArray.push(i);
  }
  return starArray;
};

export const services = [
  {
    imgURL: truckFast,
    label: "Free shipping",
    subtext: "Enjoy seamless shopping with our complimentary shipping service.",
  },
  {
    imgURL: shieldTick,
    label: "Secure Payment",
    subtext:
      "Experience worry-free transactions with our secure payment options.",
  },
  {
    imgURL: support,
    label: "Love to help you",
    subtext: "Our dedicated team is here to assist you every step of the way.",
  },
];

export const reviews = [
  {
    imgURL: customer1,
    customerName: "Morich Brown",
    rating: 4.5,
    feedback:
      "The attention to detail and the quality of the product exceeded my expectations. Highly recommended!",
  },
  {
    imgURL: customer2,
    customerName: "Lota Mongeskar",
    rating: 4.5,
    feedback:
      "The product not only met but exceeded my expectations. I'll definitely be a returning customer!",
  },
];

export const footerLinks = [
  {
    title: "Products",
    links: [
      { name: "Air Force 1", link: "/" },
      { name: "Air Max 1", link: "/" },
      { name: "Air Jordan 1", link: "/" },
      { name: "Air Force 2", link: "/" },
      { name: "Nike Waffle Racer", link: "/" },
      { name: "Nike Cortez", link: "/" },
    ],
  },
  {
    title: "Help",
    links: [
      { name: "About us", link: "/" },
      { name: "FAQs", link: "/" },
      { name: "How it works", link: "/" },
      { name: "Privacy policy", link: "/" },
      { name: "Payment policy", link: "/" },
    ],
  },
  {
    title: "Get in touch",
    links: [
      {
        name: "customer@jayfootwears.com",
        link: "mailto:customer@jayfootwears.com",
      },
      { name: "+92554862354", link: "tel:+92554862354" },
    ],
  },
];

export const socialMedia = [
  { src: facebook, alt: "facebook logo", link: "/" },
  { src: twitter, alt: "twitter logo", link: "/" },
  { src: instagram, alt: "instagram logo", link: "/" },
];

// Products
export const productsList = [
  {
    id: 1,
    name: "Nike Air Jordan",
    imgURL: shoe4,
    price: "200.0",
    rating: 4,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 2,
    name: "Nike K-Swiss",
    imgURL: shoe5,
    price: "210.0",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 3,
    name: "Nike Air-100",
    imgURL: shoe6,
    price: "220",
    rating: 4,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 4,
    name: "Smooth N",
    imgURL: shoe7,
    price: "230.20",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 5,
    name: "Air Force 1",
    imgURL: bigShoe1,
    price: "200",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 6,
    name: "Air Max 1",
    imgURL: bigShoe2,
    price: "220",
    rating: 4,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 7,
    name: "Air Jordan 1",
    imgURL: bigShoe3,
    price: "215",
    rating: 4,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Jordan",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 8,
    name: "Puma Cali",
    imgURL: shoe9,
    price: "123",
    rating: 4,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Puma",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 9,
    name: "Addidas T-Mac 1",
    imgURL: shoe10,
    price: "210",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Addidas",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 10,
    name: "Addidas T-Mac 2",
    imgURL: shoe11,
    price: "225",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Addidas",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 11,
    name: "Addidas CourtSmash",
    imgURL: shoe12,
    price: "232",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Addidas",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 12,
    name: "Lining Alpha",
    imgURL: shoe13,
    price: "211",
    rating: 4,
    quantity: 1,
    info: {
      origin: "Made in Japan",
      company: "Lining",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 13,
    name: "Lining Elite",
    imgURL: shoe14,
    price: "212",
    rating: 4,
    quantity: 1,
    info: {
      origin: "Made in Japan",
      company: "Lining",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 14,
    name: "Nike Ambush",
    imgURL: shoe15,
    price: "252",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 15,
    name: "Nike Air Max 90",
    imgURL: shoe16,
    price: "239",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 16,
    name: "Hoka Bondi 8",
    imgURL: shoe17,
    price: "218",
    rating: 4,
    quantity: 1,
    info: {
      origin: "Made in Vietnam",
      company: "Hika",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 17,
    name: "Michael Kors",
    imgURL: shoe18,
    price: "225",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Jordan",
      soleMaterial: "Leather",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 18,
    name: "Nike Kobe Bryant X-Mid",
    imgURL: shoe19,
    price: "223",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 19,
    name: "Mephisto Yael",
    imgURL: shoe20,
    price: "230",
    rating: 4,
    quantity: 1,
    info: {
      origin: "Made in Japan",
      company: "Mephisto",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 20,
    name: "Remonte D1310-81 Rangez",
    imgURL: shoe21,
    price: "200",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in China",
      company: "Remonte",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 21,
    name: "GEOX D02AQA 02211",
    imgURL: shoe22,
    price: "201",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in China",
      company: "GEOX",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 22,
    name: "Alviero Martini",
    imgURL: shoe23,
    price: "231",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in Hong Kong",
      company: "Alviero",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 23,
    name: "Nike Cortez",
    imgURL: shoe8,
    price: "229",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 24,
    name: "Schuhe Neapel Tron",
    imgURL: shoe24,
    price: "214",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in Russia",
      company: "Ara Damen",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 25,
    name: "Drena",
    imgURL: shoe25,
    price: "232",
    rating: 4,
    quantity: 1,
    info: {
      origin: "Made in Vietnam",
      company: "FinnComfort",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 26,
    name: "The Kobe Ice Blue",
    imgURL: shoe26,
    price: "320",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Addidas",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 27,
    name: "Air Jordan 14",
    imgURL: shoe27,
    price: "360",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Jordan",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 28,
    name: "Nike Zoom Hyperflight",
    imgURL: shoe28,
    price: "238",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Nike",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 29,
    name: "Burberry Vintage",
    imgURL: shoe29,
    price: "214",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Burberry",
      soleMaterial: "Leather",
      closureType: "Laceless",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
  {
    id: 30,
    name: "Addidas Crazy 1",
    imgURL: shoe30,
    price: "355",
    rating: 5,
    quantity: 1,
    info: {
      origin: "Made in USA",
      company: "Addidas",
      soleMaterial: "Rubber",
      closureType: "Lace-up",
      sizes: [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
    },
  },
];
